const instruction = [
  "Create Metadata Account",
  "Update Metadata Account",
  "Deprecated Create Master Edition",
  "Deprecated Mint New Edition From Master Edition Via Printing Token",
  "Update Primary Sale Happened Via Token",
  "Deprecated Set Reservation List",
  "Deprecated Create Reservation List",
  "Sign Metadata",
  "Deprecated Mint Printing Tokens Via Token",
  "Deprecated Mint Printing Tokens",
  "Create Master Edition",
  "Mint New Edition From Master Edition Via Token",
  "Convert Master Edition V1 To V2",
  "Mint New Edition From Master Edition Via Vault Proxy",
  "Puff Metadata",
  "Update Metadata Account V2",
  "Create Metadata Account V2",
  "Create Master Edition V3",
  "Verify Collection",
  "Utilize",
  "Approve Use Authority",
  "Revoke Use Authority",
  "Unverify Collection",
  "Approve Collection Authority",
  "Revoke Collection Authority",
  "Set And Verify Collection",
  "Freeze Delegated Account",
  "Thaw Delegated Account",
  "Remove Creator Verification",
  "Burn Nft",
  "Verify Sized Collection Item",
  "Unverify Sized Collection Item",
  "Set And Verify Sized Collection Item",
  "Create Metadata Account V3",
  "Set Collection Size",
  "Set Token Standard",
  "Bubblegum Set Collection Size",
];

(({ data }, { typeParser }) => {
  return typeParser(data, instruction);
})(d, h, m);
