const instruction = {
  0: "initGlobalConfig",
  1: "updateGlobalConfig",
  2: "initOracleConfig",
  3: "updateOracleConfig",
  4: "initFund",
  5: "updateFundState",
  6: "addAsset",
  7: "removeAsset",
  8: "deposit",
  9: "withdraw",
  10: "exchange",
  11: "closeAccount",
  12: "settle",
  13: "initCreditAccount",
  14: "exchangeDirect",
  15: "closeSettleAccount",
  16: "initOpenOrders",
  17: "splitInvestor",
  18: "calculateExitValue",
  19: "withdrawSettle",
  20: "depositIntoCredit",
  21: "creditDeposit",
  22: "initialDeposit",
  24: "exchangeDirectAMM",
  25: "verifyCreditAccountBalance",
  26: "exchangeRouteIn",
  27: "exchangeRouteOut",
  28: "initMangoAccount",
  29: "depositToMango",
  30: "withdrawFromMango",
  31: "placePerpOrderOnMango",
  32: "cancelPerpOrderOnMango",
  33: "settleFeesOnMango",
  34: "settleMangoAccount",
  35: "creditDepositV2",
  36: "prepareMangoForWithdrawalReduce",
  37: "fixCreditAccount",
  38: "prepareMangoForWithdrawalWithdraw",
  39: "initFundMeta",
  40: "initMangoAdvancedOrders",
  41: "modifyMangoAccountName",
  42: "addMangoAdvancedOrder",
  43: "removeMangoAdvancedOrder",
  44: "mangoSettleAll",
  45: "prepareMangoForWithdrawalAdvancedReduce",
  46: "removeAssetWithBurn",
  47: "closeMangoAccount",
  48: "lockInvestorAccount",
  49: "unlockInvestorAccount",
  50: "partialSettle",
  51: "approveGuard",
  52: "revokeGuard",
  53: "setGuard",
  54: "addToWhitelist",
  55: "removeFromWhitelist",
  56: "parseOracle",
};

(({ data }, { typeParser }) => {
  return typeParser(data, instruction);
})(d, h, m);
